'use strict';

/**
 * ============================================================
 *  Omie Table Registry — declarative configuration
 * ============================================================
 *
 *  Single source of truth for every Omie endpoint the pipeline
 *  syncs to Supabase. NO raw / NO jsonb columns: every Omie
 *  field maps to its own typed Postgres column. Array fields
 *  (line items, characteristics, etc.) are extracted into
 *  dedicated child tables.
 *
 *  Per-entry fields
 *  ----------------
 *
 *    name                Internal entity slug (CLI / sync_log key).
 *    table               Supabase parent table name.
 *    endpoint            Omie API path (e.g. "geral/clientes").
 *    action              Omie API call name (e.g. "ListarClientes").
 *    listKey             Response property that holds the records.
 *                        Generic extractor auto-detects when wrong.
 *    idFields            Ordered list of source fields to use as PK.
 *                        First non-null wins. SHA-1 hash fallback.
 *    pkType              'text' (default) | 'bigint'.
 *    params              Extra params merged into every request.
 *
 *  Pagination control
 *  ------------------
 *
 *    paginationStyle     'standard' (default — pagina/registros_por_pagina/total_de_paginas)
 *                        'new'      (nPagina/nRegPorPagina/nTotPaginas)
 *                        'nfe'      (nPagina/nRegistrosPorPagina/nTotalPaginas)
 *                        'pedidocompra' (nPagina/nRegsPorPagina/nTotalPaginas)
 *    paginated           false → single call, no pagination params.
 *    pageParam,
 *    sizeParam,
 *    totalPagesField     Manual overrides (rarely needed).
 *
 *  Date filters
 *  ------------
 *
 *    sinceDateField      Incremental sync sends this filter
 *                        (DD/MM/YYYY) when a since-timestamp exists.
 *    sinceEndDateField   Companion start/end filter.
 *    defaultSinceDays    Fallback lookback in days when `since`
 *                        is null and the endpoint requires dates.
 *
 *  Columns (one Postgres column per Omie field)
 *  --------------------------------------------
 *
 *    columns             Array of {name, from, type?} mapping a JSON
 *                        path in the Omie record to a typed Postgres
 *                        column. Type-converted by the transformer.
 *
 *      name              Postgres column name (snake_case).
 *      from              JSON path. Dot notation for nested:
 *                        'cabecalho.nNF' → record.cabecalho.nNF.
 *      type              'text' (default) | 'numeric' | 'bigint' |
 *                        'date' | 'timestamptz' | 'boolean' |
 *                        'boolean_inverted'.
 *                          - boolean: Omie 'S' → true, 'N' → false
 *                          - boolean_inverted: 'S' → false, 'N' → true
 *                            (used to flip inativo → ativo, etc.)
 *
 *  Children (arrays-of-objects pivoted into child tables)
 *  ------------------------------------------------------
 *
 *    children            Array of nested-array definitions. Each emits
 *                        a separate Postgres table whose rows are the
 *                        line-items of the array, with a foreign-key
 *                        column pointing back at the parent omie_id.
 *
 *      table             Child Postgres table name.
 *      listFrom          Path to the array on the parent record
 *                        (dot notation; e.g. 'det' or 'pedido.det').
 *      parentRefColumn   Column on the child table holding parent PK.
 *      idFields          Fields on each child record to use as its PK.
 *                        First non-null wins; fallback is a stable
 *                        hash of (parent_id, row_index, content).
 *      pkType            'text' (default) | 'bigint'.
 *      columns           Same shape as parent columns.
 *      childChildren     Recursion: a child may itself have children.
 *
 *  Lifecycle
 *  ---------
 *
 *    tier                'critical' | 'important' | 'optional' | 'industry'
 *    phase               1..7 (lookups → industry-specific)
 *    purpose             Human description.
 *    enabled             true|false. Forces opt-in/out regardless of tier.
 *    note                Free-text note shown beside disabled entries.
 *    legacy              true for hand-tuned core entities whose
 *                        omie_id is bigint. Used by the schema
 *                        generator to apply FK constraints and to
 *                        bypass the registry-driven extractor in
 *                        favour of the bespoke one when needed.
 * ============================================================
 */

const TABLES = [
  // ─── PHASE 0 — Hand-tuned legacy entities ──────────────────────────────
  // These eight entities use bespoke extractors (src/extractors/) but
  // share the same registry-driven transformer / schema generator as
  // every other table. Their omie_id is bigint to preserve FK joins.

  {
    name: 'clients',
    table: 'omie_clients',
    endpoint: 'geral/clientes',
    action: 'ListarClientes',
    listKey: 'clientes_cadastro',
    idFields: ['codigo_cliente_omie'],
    pkType: 'bigint',
    params: { apenas_importado_api: 'N' },
    tier: 'critical',
    phase: 0,
    legacy: true,
    purpose: 'Customers & suppliers (CRM master)',
    columns: [
      { name: 'codigo_cliente_omie',        from: 'codigo_cliente_omie',        type: 'bigint' },
      { name: 'codigo_cliente_integracao',  from: 'codigo_cliente_integracao' },
      { name: 'razao_social',               from: 'razao_social' },
      { name: 'nome_fantasia',              from: 'nome_fantasia' },
      { name: 'cnpj_cpf',                   from: 'cnpj_cpf' },
      { name: 'inscricao_estadual',         from: 'inscricao_estadual' },
      { name: 'inscricao_municipal',        from: 'inscricao_municipal' },
      { name: 'inscricao_suframa',          from: 'inscricao_suframa' },
      { name: 'email',                      from: 'email' },
      { name: 'homepage',                   from: 'homepage' },
      { name: 'cnae',                       from: 'cnae' },
      { name: 'tipo_atividade',             from: 'tipo_atividade' },
      { name: 'optante_simples_nacional',   from: 'optante_simples_nacional', type: 'boolean' },
      { name: 'produtor_rural',             from: 'produtor_rural',           type: 'boolean' },
      { name: 'contribuinte',               from: 'contribuinte' },
      { name: 'exterior',                   from: 'exterior',                 type: 'boolean' },
      { name: 'pessoa_fisica',              from: 'pessoa_fisica',            type: 'boolean' },
      { name: 'bloqueado',                  from: 'bloqueado',                type: 'boolean' },
      { name: 'bloquear_faturamento',       from: 'bloquear_faturamento',     type: 'boolean' },
      { name: 'inativo',                    from: 'inativo',                  type: 'boolean' },

      { name: 'observacao',                 from: 'observacao' },
      { name: 'pais',                       from: 'pais' },
      { name: 'estado',                     from: 'estado' },
      { name: 'cidade',                     from: 'cidade' },
      { name: 'cidade_ibge',                from: 'cidade_ibge' },
      { name: 'bairro',                     from: 'bairro' },
      { name: 'endereco',                   from: 'endereco' },
      { name: 'endereco_numero',            from: 'endereco_numero' },
      { name: 'complemento',                from: 'complemento' },
      { name: 'cep',                        from: 'cep' },
      { name: 'codigo_pais',                from: 'codigo_pais' },
      { name: 'telefone1_ddd',              from: 'telefone1_ddd' },
      { name: 'telefone1_numero',           from: 'telefone1_numero' },
      { name: 'telefone2_ddd',              from: 'telefone2_ddd' },
      { name: 'telefone2_numero',           from: 'telefone2_numero' },
      { name: 'fax_ddd',                    from: 'fax_ddd' },
      { name: 'fax_numero',                 from: 'fax_numero' },
      { name: 'contato',                    from: 'contato' },
      { name: 'cargo_contato',              from: 'cargo' },
      { name: 'valor_limite_credito',       from: 'valor_limite_credito',     type: 'numeric' },
      { name: 'pessoa_fisica_dt_nasc',      from: 'dadosPF.dtNasc',           type: 'date' },
      { name: 'pessoa_fisica_sexo',         from: 'dadosPF.cSexo' },
      { name: 'pessoa_fisica_estado_civil', from: 'dadosPF.cEstCivil' },
      { name: 'banco_codigo',               from: 'dadosBancarios.codigo_banco' },
      { name: 'banco_agencia',              from: 'dadosBancarios.agencia' },
      { name: 'banco_conta_corrente',       from: 'dadosBancarios.conta_corrente' },
      { name: 'banco_doc_titular',          from: 'dadosBancarios.doc_titular' },
      { name: 'banco_nome_titular',         from: 'dadosBancarios.nome_titular' },
      { name: 'banco_transf_padrao',        from: 'dadosBancarios.transf_padrao',  type: 'boolean' },
      { name: 'entrega_endereco',           from: 'enderecoEntrega.entLogradouro' },
      { name: 'entrega_numero',             from: 'enderecoEntrega.entNumero' },
      { name: 'entrega_complemento',        from: 'enderecoEntrega.entComplemento' },
      { name: 'entrega_bairro',             from: 'enderecoEntrega.entBairro' },
      { name: 'entrega_cidade',             from: 'enderecoEntrega.entCidade' },
      { name: 'entrega_estado',             from: 'enderecoEntrega.entEstado' },
      { name: 'entrega_cep',                from: 'enderecoEntrega.entCEP' },
      { name: 'entrega_codigo_pais',        from: 'enderecoEntrega.entCodPais' },
      { name: 'rec_codigo_vendedor',        from: 'recomendacoes.codigo_vendedor',     type: 'bigint' },
      { name: 'rec_codigo_transportador',   from: 'recomendacoes.codigo_transportador', type: 'bigint' },
      { name: 'rec_gerar_boletos',          from: 'recomendacoes.gerar_boletos',       type: 'boolean' },
      { name: 'rec_numero_parcelas',        from: 'recomendacoes.numero_parcelas',     type: 'numeric' },
      { name: 'rec_observacoes',            from: 'recomendacoes.observacoes' },
      { name: 'tipo_assinante',             from: 'tipo_assinante' },
      { name: 'info_cint',                  from: 'info.cInt' },
      { name: 'info_imp_api',               from: 'info.cImpAPI' },
      { name: 'info_dt_inc',                from: 'info.dInc',                 type: 'date' },
      { name: 'info_hr_inc',                from: 'info.hInc' },
      { name: 'info_user_inc',              from: 'info.uInc' },
      { name: 'info_dt_alt',                from: 'info.dAlt',                 type: 'date' },
      { name: 'info_hr_alt',                from: 'info.hAlt' },
      { name: 'info_user_alt',              from: 'info.uAlt' },
      // Convenience boolean derived from Omie's `inativo` flag.
      { name: 'ativo',                      from: 'inativo',                   type: 'boolean_inverted' },
    ],
    children: [
      {
        table: 'omie_client_tags',
        listFrom: 'tags',
        parentRefColumn: 'codigo_cliente_omie',
        idFields: ['tag'],
        columns: [
          { name: 'tag', from: 'tag' },
        ],
      },
      {
        table: 'omie_client_caracteristicas',
        listFrom: 'caracteristicas',
        parentRefColumn: 'codigo_cliente_omie',
        idFields: ['cCodCaract'],
        columns: [
          { name: 'cod_caract', from: 'cCodCaract' },
          { name: 'caracteristica', from: 'cCaracteristica' },
          { name: 'conteudo', from: 'cConteudo' },
        ],
      },
      {
        table: 'omie_client_contatos',
        listFrom: 'contatos',
        parentRefColumn: 'codigo_cliente_omie',
        idFields: ['cCodCont', 'codigo_contato'],
        columns: [
          { name: 'cod_contato',        from: 'cCodCont' },
          { name: 'nome',               from: 'cNome' },
          { name: 'sobrenome',          from: 'cSobrenome' },
          { name: 'cargo',              from: 'cCargo' },
          { name: 'email',              from: 'cEmail' },
          { name: 'fone',               from: 'cFone' },
          { name: 'cpf',                from: 'cCPF' },
        ],
      },
    ],
  },

  {
    name: 'orders',
    table: 'omie_orders',
    endpoint: 'produtos/pedido',
    action: 'ListarPedidos',
    listKey: 'pedido_venda_produto',
    idFields: ['cabecalho.codigo_pedido'],
    pkType: 'bigint',
    params: { etapa: '' },
    tier: 'critical',
    phase: 0,
    legacy: true,
    purpose: 'Sales orders',
    columns: [
      { name: 'codigo_pedido',              from: 'cabecalho.codigo_pedido',          type: 'bigint' },
      { name: 'codigo_pedido_integracao',   from: 'cabecalho.codigo_pedido_integracao' },
      { name: 'numero_pedido',              from: 'cabecalho.numero_pedido' },
      { name: 'codigo_cliente',             from: 'cabecalho.codigo_cliente',         type: 'bigint' },
      { name: 'codigo_cenario',             from: 'cabecalho.codigo_cenario',         type: 'bigint' },
      { name: 'codigo_local_estoque',       from: 'cabecalho.codigo_local_estoque',   type: 'bigint' },
      { name: 'codigo_parcela',             from: 'cabecalho.codigo_parcela' },
      { name: 'data_previsao',              from: 'cabecalho.data_previsao',          type: 'date' },
      { name: 'etapa',                      from: 'cabecalho.etapa' },
      { name: 'qtde_itens',                 from: 'cabecalho.qtde_itens',             type: 'numeric' },
      { name: 'origem_pedido',              from: 'cabecalho.origem_pedido' },
      { name: 'pedido_status',              from: 'cabecalho.pedido_status' },
      // informacoes_adicionais
      { name: 'codigo_categoria',           from: 'informacoes_adicionais.codigo_categoria' },
      { name: 'codigo_conta_corrente',      from: 'informacoes_adicionais.codigo_conta_corrente', type: 'bigint' },
      { name: 'codigo_departamento',        from: 'informacoes_adicionais.codigo_departamento' },
      { name: 'codigo_tipo_documento',      from: 'informacoes_adicionais.codigo_tipo_documento' },
      { name: 'codigo_vendedor',            from: 'informacoes_adicionais.codVend',       type: 'bigint' },
        { name: 'cancelado', from: 'infoCadastro.cancelado', type: 'boolean' },
        { name: 'faturado', from: 'infoCadastro.faturado', type: 'boolean' },
        { name: 'denegado', from: 'infoCadastro.denegado', type: 'boolean' },
        { name: 'devolvido', from: 'infoCadastro.devolvido', type: 'boolean' },
        { name: 'autorizado', from: 'infoCadastro.autorizado', type: 'boolean' },
      { name: 'codigo_projeto',             from: 'informacoes_adicionais.codProj',               type: 'bigint' },
      { name: 'consumidor_final',           from: 'informacoes_adicionais.consumidor_final' },
      { name: 'enviar_email',               from: 'informacoes_adicionais.enviar_email',          type: 'boolean' },
      { name: 'numero_pedido_cliente',      from: 'informacoes_adicionais.numero_pedido_cliente' },
      { name: 'obs_venda',                  from: 'informacoes_adicionais.obs_venda' },
      { name: 'obs_internas',               from: 'informacoes_adicionais.obs_internas' },
      { name: 'utilizar_emails',            from: 'informacoes_adicionais.utilizar_emails' },
      // frete
      { name: 'codigo_transportadora',      from: 'frete.codigo_transportadora',     type: 'bigint' },
      { name: 'modalidade_frete',           from: 'frete.modalidade_frete' },
      { name: 'placa_veiculo',              from: 'frete.placa_veiculo' },
      { name: 'qtde_volumes',               from: 'frete.qtde_volumes',              type: 'numeric' },
      { name: 'peso_bruto',                 from: 'frete.peso_bruto',                type: 'numeric' },
      { name: 'peso_liquido',               from: 'frete.peso_liquido',              type: 'numeric' },
      { name: 'uf_veiculo',                 from: 'frete.uf_veiculo' },
      { name: 'valor_frete',                from: 'frete.valor_frete',               type: 'numeric' },
      { name: 'especie_volumes',            from: 'frete.especie_volumes' },
      { name: 'marca_volumes',              from: 'frete.marca_volumes' },
      // total_pedido
      { name: 'valor_mercadorias',          from: 'total_pedido.valor_mercadorias',  type: 'numeric' },
      { name: 'valor_total_pedido',         from: 'total_pedido.valor_total_pedido', type: 'numeric' },
      { name: 'valor_descontos',            from: 'total_pedido.valor_descontos',    type: 'numeric' },
      { name: 'valor_acrescimos',           from: 'total_pedido.valor_acrescimos',   type: 'numeric' },
      // exportacao
      { name: 'export_estado_embarque',     from: 'exportacao.cEstadoEmbarque' },
      { name: 'export_local_embarque',      from: 'exportacao.cLocalEmbarque' },
      // observacoes (legacy nested obs)
      { name: 'obs_pedido',                 from: 'observacoes.obs_pedido' },
      // info
      { name: 'info_cint',                  from: 'infoCadastro.cInt' },
      { name: 'info_imp_api',               from: 'infoCadastro.cImpAPI' },
      { name: 'info_dt_inc',                from: 'infoCadastro.dInc',               type: 'date' },
      { name: 'info_hr_inc',                from: 'infoCadastro.hInc' },
      { name: 'info_user_inc',              from: 'infoCadastro.uInc' },
      { name: 'info_dt_alt',                from: 'infoCadastro.dAlt',               type: 'date' },
      { name: 'info_hr_alt',                from: 'infoCadastro.hAlt' },
      { name: 'info_user_alt',              from: 'infoCadastro.uAlt' },
    ],
    children: [
      {
        table: 'omie_order_items',
        listFrom: 'det',
        parentRefColumn: 'codigo_pedido',
        idFields: ['ide.codigo_item', 'produto.codigo_produto'],
        columns: [
          { name: 'codigo_item',              from: 'ide.codigo_item',                   type: 'bigint' },
          { name: 'codigo_item_integracao',   from: 'ide.codigo_item_integracao' },
          { name: 'simples_nacional',         from: 'ide.simples_nacional' },
          { name: 'codigo_produto',           from: 'produto.codigo_produto',            type: 'bigint' },
          { name: 'codigo_produto_integ',     from: 'produto.codigo_produto_integracao' },
          { name: 'cfop',                     from: 'produto.cfop' },
          { name: 'cod_int_tab_preco',        from: 'produto.cod_int_tab_preco' },
          { name: 'codigo_tabela_preco',      from: 'produto.codigo_tabela_preco',       type: 'bigint' },
          { name: 'descricao',                from: 'produto.descricao' },
          { name: 'descricao_complementar',   from: 'produto.descr_compl' },
          { name: 'ean',                      from: 'produto.ean' },
          { name: 'ncm',                      from: 'produto.ncm' },
          { name: 'tipo_desconto',            from: 'produto.tipo_desconto' },
          { name: 'unidade',                  from: 'produto.unidade' },
          { name: 'quantidade',               from: 'produto.quantidade',                type: 'numeric' },
          { name: 'valor_unitario',           from: 'produto.valor_unitario',            type: 'numeric' },
          { name: 'valor_deducao',            from: 'produto.valor_deducao',             type: 'numeric' },
          { name: 'percentual_desconto',      from: 'produto.percentual_desconto',       type: 'numeric' },
          { name: 'valor_desconto',           from: 'produto.valor_desconto',            type: 'numeric' },
          { name: 'valor_mercadoria',         from: 'produto.valor_mercadoria',          type: 'numeric' },
          { name: 'valor_total',              from: 'produto.valor_total',               type: 'numeric' },
          { name: 'reservado',                from: 'produto.reservado',                 type: 'boolean' },
          // inventario
          { name: 'inventario_codigo_local_estoque', from: 'inventario.codigo_local_estoque', type: 'bigint' },
          { name: 'inventario_motivo_baixa',         from: 'inventario.cMotivoBaixa' },
          { name: 'inventario_id_lote',              from: 'inventario.idLote' },
          { name: 'inventario_quantidade',           from: 'inventario.quantidade',     type: 'numeric' },
          // observacao
          { name: 'obs_item',                 from: 'observacao.obs_item' },
          // tributacao (ICMS)
          { name: 'icms_base',                from: 'imposto_icms.base_icms',            type: 'numeric' },
          { name: 'icms_valor',               from: 'imposto_icms.valor_icms',           type: 'numeric' },
          { name: 'icms_aliquota',            from: 'imposto_icms.aliquota_icms',        type: 'numeric' },
          { name: 'icms_cst',                 from: 'imposto_icms.cst_icms' },
          { name: 'icms_origem',              from: 'imposto_icms.modalidade_icms' },
          // info
          { name: 'info_dt_inc',              from: 'info.dInc',                         type: 'date' },
          { name: 'info_hr_inc',              from: 'info.hInc' },
          { name: 'info_dt_alt',              from: 'info.dAlt',                         type: 'date' },
          { name: 'info_hr_alt',              from: 'info.hAlt' },
        ],
      },
      {
        table: 'omie_order_lancamentos',
        listFrom: 'lista_parcelas.parcela',
        parentRefColumn: 'codigo_pedido',
        idFields: ['numero_parcela', 'codigo_lancamento'],
        columns: [
          { name: 'numero_parcela',           from: 'numero_parcela',                    type: 'bigint' },
          { name: 'codigo_lancamento',        from: 'codigo_lancamento',                 type: 'bigint' },
          { name: 'data_vencimento',          from: 'data_vencimento',                   type: 'date' },
          { name: 'valor',                    from: 'valor',                             type: 'numeric' },
          { name: 'percentual',               from: 'percentual',                        type: 'numeric' },
          { name: 'meio_pagamento',           from: 'meio_pagamento' },
          { name: 'quitado',                  from: 'quitado',                           type: 'boolean' },
        ],
      },
    ],
  },

  {
    name: 'receivable',
    table: 'omie_accounts_receivable',
    endpoint: 'financas/contareceber',
    action: 'ListarContasReceber',
    listKey: 'conta_receber_cadastro',
    idFields: ['codigo_lancamento_omie'],
    pkType: 'bigint',
    tier: 'critical',
    phase: 0,
    legacy: true,
    purpose: 'Accounts receivable',
    preserveFilledFields: true,
    columns: [
      { name: 'codigo_lancamento_omie',     from: 'codigo_lancamento_omie',           type: 'bigint' },
      { name: 'codigo_lancamento_integ',    from: 'codigo_lancamento_integracao' },
      { name: 'codigo_cliente_fornecedor',  from: 'codigo_cliente_fornecedor',        type: 'bigint' },
      { name: 'codigo_cliente_integ',       from: 'codigo_cliente_fornecedor_integracao' },
      { name: 'numero_documento',           from: 'numero_documento' },
      { name: 'numero_documento_fiscal',    from: 'numero_documento_fiscal' },
      { name: 'numero_parcela',             from: 'numero_parcela' },
      { name: 'data_emissao',               from: 'data_emissao',                     type: 'date' },
      { name: 'data_vencimento',            from: 'data_vencimento',                  type: 'date' },
      { name: 'data_previsao',              from: 'data_previsao',                    type: 'date' },
      { name: 'data_pagamento',             from: 'data_pagamento',                   type: 'date' },
      { name: 'data_registro',              from: 'data_registro',                    type: 'date' },
      { name: 'valor_documento',            from: 'valor_documento',                  type: 'numeric' },
      { name: 'valor_recebido',             from: 'valor_recebido',                   type: 'numeric' },
      { name: 'valor_pis',                  from: 'valor_pis',                        type: 'numeric' },
      { name: 'valor_cofins',               from: 'valor_cofins',                     type: 'numeric' },
      { name: 'valor_csll',                 from: 'valor_csll',                       type: 'numeric' },
      { name: 'valor_ir',                   from: 'valor_ir',                         type: 'numeric' },
      { name: 'valor_iss',                  from: 'valor_iss',                        type: 'numeric' },
      { name: 'valor_inss',                 from: 'valor_inss',                       type: 'numeric' },
      { name: 'percentual_juros',           from: 'juros.percentual_juros',           type: 'numeric' },
      { name: 'data_juros',                 from: 'juros.data_juros',                 type: 'date' },
      { name: 'codigo_categoria',           from: 'codigo_categoria' },
      { name: 'codigo_tipo_documento',      from: 'codigo_tipo_documento' },
      { name: 'codigo_conta_corrente',      from: 'id_conta_corrente',                type: 'bigint' },
      { name: 'codigo_projeto',             from: 'codigo_projeto',                   type: 'bigint' },
      { name: 'codigo_vendedor',            from: 'codigo_vendedor',                  type: 'bigint' },
      { name: 'codigo_departamento',        from: 'departamentos.cCodDepartamento' },
      { name: 'status_titulo',              from: 'status_titulo' },
      { name: 'operacao',                   from: 'operacao' },
      { name: 'observacao',                 from: 'observacao' },
      { name: 'codigo_barras',              from: 'boleto.codigo_barras' },
      { name: 'numero_boleto',              from: 'boleto.numero_boleto' },
      { name: 'codigo_barras_dac',          from: 'boleto.codigo_barras_dac' },
      { name: 'nosso_numero',               from: 'boleto.nosso_numero' },
      { name: 'info_cint',                  from: 'info.cInt' },
      { name: 'info_imp_api',               from: 'info.cImpAPI' },
      { name: 'info_dt_inc',                from: 'info.dInc',                         type: 'date' },
      { name: 'info_hr_inc',                from: 'info.hInc' },
      { name: 'info_user_inc',              from: 'info.uInc' },
      { name: 'info_dt_alt',                from: 'info.dAlt',                         type: 'date' },
      { name: 'info_hr_alt',                from: 'info.hAlt' },
      { name: 'info_user_alt',              from: 'info.uAlt' },
      { name: 'distribuicao_codigo',        from: 'distr_categorias.cCodCateg' },
      { name: 'distribuicao_valor',         from: 'distr_categorias.nValor',           type: 'numeric' },
      { name: 'distribuicao_percentual',    from: 'distr_categorias.nPercentual',      type: 'numeric' },
    ],
  },

  {
    name: 'payable',
    table: 'omie_accounts_payable',
    endpoint: 'financas/contapagar',
    action: 'ListarContasPagar',
    listKey: 'conta_pagar_cadastro',
    idFields: ['codigo_lancamento_omie'],
    pkType: 'bigint',
    tier: 'critical',
    phase: 0,
    legacy: true,
    purpose: 'Accounts payable',
    preserveFilledFields: true,
    columns: [
      { name: 'codigo_lancamento_omie',     from: 'codigo_lancamento_omie',           type: 'bigint' },
      { name: 'codigo_lancamento_integ',    from: 'codigo_lancamento_integracao' },
      { name: 'codigo_cliente_fornecedor',  from: 'codigo_cliente_fornecedor',        type: 'bigint' },
      { name: 'codigo_cliente_integ',       from: 'codigo_cliente_fornecedor_integracao' },
      { name: 'numero_documento',           from: 'numero_documento' },
      { name: 'numero_documento_fiscal',    from: 'numero_documento_fiscal' },
      { name: 'numero_parcela',             from: 'numero_parcela' },
      { name: 'data_emissao',               from: 'data_emissao',                     type: 'date' },
      { name: 'data_vencimento',            from: 'data_vencimento',                  type: 'date' },
      { name: 'data_previsao',              from: 'data_previsao',                    type: 'date' },
      { name: 'data_pagamento',             from: 'data_pagamento',                   type: 'date' },
      { name: 'data_registro',              from: 'data_registro',                    type: 'date' },
      { name: 'valor_documento',            from: 'valor_documento',                  type: 'numeric' },
      { name: 'valor_pago',                 from: 'valor_pago',                       type: 'numeric' },
      { name: 'valor_pis',                  from: 'valor_pis',                        type: 'numeric' },
      { name: 'valor_cofins',               from: 'valor_cofins',                     type: 'numeric' },
      { name: 'valor_csll',                 from: 'valor_csll',                       type: 'numeric' },
      { name: 'valor_ir',                   from: 'valor_ir',                         type: 'numeric' },
      { name: 'valor_iss',                  from: 'valor_iss',                        type: 'numeric' },
      { name: 'valor_inss',                 from: 'valor_inss',                       type: 'numeric' },
      { name: 'codigo_categoria',           from: 'codigo_categoria' },
      { name: 'codigo_tipo_documento',      from: 'codigo_tipo_documento' },
      { name: 'codigo_conta_corrente',      from: 'id_conta_corrente',                type: 'bigint' },
      { name: 'codigo_projeto',             from: 'codigo_projeto',                   type: 'bigint' },
      { name: 'codigo_vendedor',            from: 'codigo_vendedor',                  type: 'bigint' },
      { name: 'codigo_departamento',        from: 'departamentos.cCodDepartamento' },
      { name: 'status_titulo',              from: 'status_titulo' },
      { name: 'operacao',                   from: 'operacao' },
      { name: 'observacao',                 from: 'observacao' },
      { name: 'codigo_barras',              from: 'boleto.codigo_barras' },
      { name: 'numero_boleto',              from: 'boleto.numero_boleto' },
      { name: 'nosso_numero',               from: 'boleto.nosso_numero' },
      { name: 'info_cint',                  from: 'info.cInt' },
      { name: 'info_imp_api',               from: 'info.cImpAPI' },
      { name: 'info_dt_inc',                from: 'info.dInc',                         type: 'date' },
      { name: 'info_hr_inc',                from: 'info.hInc' },
      { name: 'info_user_inc',              from: 'info.uInc' },
      { name: 'info_dt_alt',                from: 'info.dAlt',                         type: 'date' },
      { name: 'info_hr_alt',                from: 'info.hAlt' },
      { name: 'info_user_alt',              from: 'info.uAlt' },
    ],
    children: [
      {
        table: 'omie_accounts_payable_categorias',
        listFrom: 'categorias',
        parentRefColumn: 'parent_omie_id',
        idFields: ['codigo_categoria'],
        columns: [
          { name: 'cod_categoria', from: 'codigo_categoria' },
          { name: 'valor',         from: 'valor',       type: 'numeric' },
          { name: 'percentual',    from: 'percentual',  type: 'numeric' },
        ],
      },
    ],
  },

  {
    name: 'services',
    table: 'omie_service_orders',
    endpoint: 'servicos/os',
    action: 'ListarOS',
    listKey: 'osCadastro',
    idFields: ['Cabecalho.nCodOS'],
    pkType: 'bigint',
    tier: 'critical',
    phase: 0,
    legacy: true,
    purpose: 'Service orders (OS)',
    columns: [
      { name: 'codigo_os',                  from: 'Cabecalho.nCodOS',                  type: 'bigint' },
      { name: 'codigo_cliente',             from: 'Cabecalho.nCodCli',                 type: 'bigint' },
      { name: 'numero_os',                  from: 'Cabecalho.cNumOS' },
      { name: 'codigo_parcela',             from: 'Cabecalho.cCodParc' },
      { name: 'data_previsao',              from: 'Cabecalho.dDtPrevisao',             type: 'date' },
      { name: 'data_faturamento',           from: 'Cabecalho.dDtFaturamento',          type: 'date' },
      { name: 'etapa',                      from: 'Cabecalho.cEtapa' },
      { name: 'codigo_local_prest',         from: 'Cabecalho.cCodLocPrest' },
      { name: 'codigo_intermediador',       from: 'Cabecalho.nCodIntermediador',       type: 'bigint' },
      { name: 'observacoes',                from: 'Cabecalho.cObsOS' },
      // InformacoesAdicionais
      { name: 'codigo_categoria',           from: 'InformacoesAdicionais.cCodCateg' },
      { name: 'codigo_departamento',        from: 'InformacoesAdicionais.cCodDepart' },
      { name: 'codigo_projeto',             from: 'InformacoesAdicionais.nCodProj',    type: 'bigint' },
      { name: 'codigo_conta_corrente',      from: 'InformacoesAdicionais.nCodCC',      type: 'bigint' },
      { name: 'codigo_vendedor',            from: 'InformacoesAdicionais.nCodVend',    type: 'bigint' },
      { name: 'codigo_natureza',            from: 'InformacoesAdicionais.cNatOper' },
      { name: 'numero_pedido_cliente',      from: 'InformacoesAdicionais.cNumPedido' },
      // ValoresTotais
      { name: 'valor_total_servicos',       from: 'ValoresTotais.nValorTotalServicos', type: 'numeric' },
      { name: 'valor_total_pecas',          from: 'ValoresTotais.nValorTotalPecas',    type: 'numeric' },
      { name: 'valor_outras_ret',           from: 'ValoresTotais.nValorOutrasRet',     type: 'numeric' },
      { name: 'valor_total_outros',         from: 'ValoresTotais.nValorTotalOutros',   type: 'numeric' },
      { name: 'valor_total_iss',            from: 'ValoresTotais.nValorTotalISS',      type: 'numeric' },
      { name: 'valor_total_pis',            from: 'ValoresTotais.nValorTotalPIS',      type: 'numeric' },
      { name: 'valor_total_cofins',         from: 'ValoresTotais.nValorTotalCOFINS',   type: 'numeric' },
      { name: 'valor_total_csll',           from: 'ValoresTotais.nValorTotalCSLL',     type: 'numeric' },
      { name: 'valor_total_ir',             from: 'ValoresTotais.nValorTotalIR',       type: 'numeric' },
      { name: 'valor_total_inss',           from: 'ValoresTotais.nValorTotalINSS',     type: 'numeric' },
      // InformacoesCadastro
      { name: 'info_cint',                  from: 'InformacoesCadastro.cCadIntegracao' },
      { name: 'info_dt_inc',                from: 'InformacoesCadastro.dInc',          type: 'date' },
      { name: 'info_hr_inc',                from: 'InformacoesCadastro.hInc' },
      { name: 'info_user_inc',              from: 'InformacoesCadastro.uInc' },
      { name: 'info_dt_alt',                from: 'InformacoesCadastro.dAlt',          type: 'date' },
      { name: 'info_hr_alt',                from: 'InformacoesCadastro.hAlt' },
      { name: 'info_user_alt',              from: 'InformacoesCadastro.uAlt' },
    ],
    children: [
      {
        table: 'omie_service_order_items',
        listFrom: 'ServicosPrestados',
        parentRefColumn: 'codigo_os',
        idFields: ['cCodServMun', 'cDescrServ'],
        columns: [
          { name: 'codigo_serv_mun',        from: 'cCodServMun' },
          { name: 'codigo_lc116',           from: 'cCodLC116' },
          { name: 'descricao_servico',      from: 'cDescrServ' },
          { name: 'quantidade',             from: 'nQtde',                            type: 'numeric' },
          { name: 'valor_unitario',         from: 'nValUnit',                         type: 'numeric' },
          { name: 'valor_total',            from: 'nValTotal',                        type: 'numeric' },
          { name: 'cnae',                   from: 'cCNAE' },
        ],
      },
      {
        table: 'omie_service_order_parcels',
        listFrom: 'Parcelas',
        parentRefColumn: 'codigo_os',
        idFields: ['nNumParcela'],
        columns: [
          { name: 'numero_parcela',         from: 'nNumParcela',                      type: 'bigint' },
          { name: 'data_vencimento',        from: 'dDtVenc',                          type: 'date' },
          { name: 'valor',                  from: 'nValor',                           type: 'numeric' },
          { name: 'percentual',             from: 'nPercentual',                      type: 'numeric' },
        ],
      },
    ],
  },

  {
    name: 'products',
    table: 'omie_products',
    endpoint: 'geral/produtos',
    action: 'ListarProdutos',
    listKey: 'produto_servico_cadastro',
    idFields: ['codigo_produto'],
    pkType: 'bigint',
    params: { filtrar_apenas_omiepdv: 'N' },
    tier: 'critical',
    phase: 0,
    legacy: true,
    purpose: 'Products catalog',
    columns: [
      { name: 'codigo_produto',             from: 'codigo_produto',                   type: 'bigint' },
      { name: 'codigo_produto_integracao',  from: 'codigo_produto_integracao' },
      { name: 'codigo',                     from: 'codigo' },
      { name: 'descricao',                  from: 'descricao' },
      { name: 'descricao_detalhada',        from: 'descr_detalhada' },
      { name: 'descricao_familia',          from: 'descricao_familia' },
      { name: 'codigo_familia',             from: 'codigo_familia',                   type: 'bigint' },
      { name: 'unidade',                    from: 'unidade' },
      { name: 'ncm',                        from: 'ncm' },
      { name: 'ean',                        from: 'ean' },
      { name: 'cest',                       from: 'cest' },
      { name: 'cfop',                       from: 'recomendacoes_fiscais.codigo_cfop' },
      { name: 'origem_mercadoria',          from: 'recomendacoes_fiscais.origem_mercadoria' },
      { name: 'csosn_icms',                 from: 'recomendacoes_fiscais.cst_icms' },
      { name: 'cst_pis',                    from: 'recomendacoes_fiscais.cst_pis' },
      { name: 'cst_cofins',                 from: 'recomendacoes_fiscais.cst_cofins' },
      { name: 'cst_ipi',                    from: 'recomendacoes_fiscais.cst_ipi' },
      { name: 'tipoItem',                   from: 'tipoItem' },
      { name: 'marca',                      from: 'marca' },
      { name: 'modelo',                     from: 'modelo' },
      { name: 'valor_unitario',             from: 'valor_unitario',                   type: 'numeric' },
      { name: 'estoque_minimo',             from: 'estoque_minimo',                   type: 'numeric' },
      { name: 'aliquota_icms',              from: 'aliquota_icms',                    type: 'numeric' },
      { name: 'aliquota_ipi',               from: 'aliquota_ipi',                     type: 'numeric' },
      { name: 'peso_bruto',                 from: 'peso_bruto',                       type: 'numeric' },
      { name: 'peso_liq',                   from: 'peso_liq',                         type: 'numeric' },
      { name: 'altura',                     from: 'altura',                           type: 'numeric' },
      { name: 'largura',                    from: 'largura',                          type: 'numeric' },
      { name: 'profundidade',               from: 'profundidade',                     type: 'numeric' },
      { name: 'dias_garantia',              from: 'dias_garantia',                    type: 'numeric' },
      { name: 'dias_crossdocking',          from: 'dias_crossdocking',                type: 'numeric' },
      { name: 'tipo_estoque',               from: 'tipo_estoque' },
      { name: 'obs_internas',               from: 'obs_internas' },
      { name: 'bloqueado',                  from: 'bloqueado',                        type: 'boolean' },
      { name: 'bloquear_exclusao',          from: 'bloquear_exclusao',                type: 'boolean' },
      { name: 'inativo',                    from: 'inativo',                          type: 'boolean' },

      { name: 'ativo',                      from: 'inativo',                          type: 'boolean_inverted' },
      { name: 'imagem_principal',           from: 'imagens.imagem_principal' },
      { name: 'info_dt_inc',                from: 'info.dInc',                         type: 'date' },
      { name: 'info_hr_inc',                from: 'info.hInc' },
      { name: 'info_user_inc',              from: 'info.uInc' },
      { name: 'info_dt_alt',                from: 'info.dAlt',                         type: 'date' },
      { name: 'info_hr_alt',                from: 'info.hAlt' },
      { name: 'info_user_alt',              from: 'info.uAlt' },
    ],
    children: [
      {
        table: 'omie_product_caract_values',
        listFrom: 'caracteristicas',
        parentRefColumn: 'codigo_produto',
        idFields: ['cCodCaract'],
        columns: [
          { name: 'codigo_caracteristica',  from: 'cCodCaract' },
          { name: 'nome_caracteristica',    from: 'cNomeCaract' },
          { name: 'conteudo',               from: 'cConteudo' },
        ],
      },
      {
        table: 'omie_product_tags',
        listFrom: 'tags',
        parentRefColumn: 'codigo_produto',
        idFields: ['tag'],
        columns: [
          { name: 'tag', from: 'tag' },
        ],
      },
      {
        table: 'omie_product_images',
        listFrom: 'imagens',
        parentRefColumn: 'codigo_produto',
        idFields: ['url_imagem'],
        columns: [
          { name: 'url_imagem', from: 'url_imagem' },
        ],
      },
    ],
  },

  {
    name: 'crm_opportunities',
    table: 'omie_crm_opportunities',
    endpoint: 'crm/oportunidades',
    action: 'ListarOportunidades',
    listKey: 'cadastros',
    idFields: ['identificacao.nCodOp'],
    pkType: 'bigint',
    sinceDateField: 'data_alteracao_inicial',
    tier: 'critical',
    phase: 0,
    legacy: true,
    purpose: 'CRM opportunities (pipeline)',
    columns: [
      { name: 'cod_oportunidade',           from: 'identificacao.nCodOp',              type: 'bigint' },
      { name: 'descricao',                  from: 'identificacao.cDesOp' },
      { name: 'codigo_conta',               from: 'identificacao.nCodConta',           type: 'bigint' },
      { name: 'codigo_contato',             from: 'identificacao.nCodContato',         type: 'bigint' },
      { name: 'codigo_vendedor',            from: 'identificacao.nCodVendedor',        type: 'bigint' },
      { name: 'codigo_origem',              from: 'identificacao.nCodOrigem',          type: 'bigint' },
      { name: 'codigo_solucao',             from: 'identificacao.nCodSolucao',         type: 'bigint' },
      { name: 'observacoes_descricao',      from: 'observacoes.cObs' },
      // fasesStatus
      { name: 'codigo_status',              from: 'fasesStatus.nCodStatus',            type: 'bigint' },
      { name: 'codigo_fase',                from: 'fasesStatus.nCodFase',              type: 'bigint' },
      { name: 'codigo_motivo_perda',        from: 'fasesStatus.nCodMotivoPerda',       type: 'bigint' },
      // ticket
      { name: 'ticket',                     from: 'ticket.nTicket',                   type: 'numeric' },
      // previsaoTemp
      { name: 'previsao_mes',               from: 'previsaoTemp.nMesPrev',            type: 'numeric' },
      { name: 'previsao_ano',               from: 'previsaoTemp.nAnoPrev',            type: 'numeric' },
      // datas
      { name: 'data_inclusao',              from: 'envolvidos.dDtInc',                type: 'date' },
      { name: 'hora_inclusao',              from: 'envolvidos.hInc' },
      { name: 'data_alteracao',             from: 'envolvidos.dDtAlt',                type: 'date' },
      { name: 'hora_alteracao',             from: 'envolvidos.hAlt' },
    ],
  },

  {
    name: 'crm_activities',
    table: 'omie_crm_activities',
    endpoint: 'crm/tarefas',
    action: 'ListarTarefas',
    listKey: 'cadastros',
    idFields: ['nCodTarefa'],
    pkType: 'bigint',
    sinceDateField: 'data_inicial',
    sinceEndDateField: 'data_final',
    defaultSinceDays: 90,
    tier: 'critical',
    phase: 0,
    legacy: true,
    purpose: 'CRM activities / tasks',
    columns: [
      { name: 'cod_tarefa',                 from: 'nCodTarefa',                       type: 'bigint' },
      { name: 'cod_oportunidade',           from: 'nCodOp',                           type: 'bigint' },
      { name: 'cod_atividade',              from: 'nCodAtividade',                    type: 'bigint' },
      { name: 'cod_usuario',                from: 'nCodUsuario',                      type: 'bigint' },
      { name: 'data',                       from: 'dData',                            type: 'date' },
      { name: 'hora',                       from: 'cHora' },
      { name: 'descricao',                  from: 'cDescricao' },
      { name: 'realizada',                  from: 'cRealizada',                       type: 'boolean' },
      { name: 'em_execucao',                from: 'cEmExecucao',                      type: 'boolean' },
    ],
  },

  // ─── PHASE 1 — Basic Lookups ─────────────────────────────────────────────

  {
    name: 'dre',
    table: 'omie_dre',
    endpoint: 'financas/contadre',
    action: 'ListarDRE',
    listKey: 'dre_cadastro',
    idFields: ['nCodCC', 'codigo'],
    tier: 'critical',
    phase: 1,
    purpose: 'Accounting chart of accounts (DRE)',
    enabled: false,
    note: 'No standalone DRE list endpoint on Omie. The DRE structure is normally derived from `omie_categories`. Re-enable only if your tenant exposes /financas/contadre/.',
  },
  {
    name: 'categories',
    table: 'omie_categories',
    endpoint: 'geral/categorias',
    action: 'ListarCategorias',
    listKey: 'categoria_cadastro',
    idFields: ['codigo', 'codigo_categoria'],
    tier: 'critical',
    phase: 1,
    purpose: 'Operational chart of accounts',
    columns: [
      { name: 'codigo',           from: 'codigo' },
      { name: 'descricao',        from: 'descricao' },
      { name: 'descricao_padrao', from: 'descricao_padrao' },
      { name: 'natureza',         from: 'natureza' },
      { name: 'tipo_categoria',   from: 'tipo_categoria' },
      { name: 'codigo_dre',       from: 'codigo_dre' },
      { name: 'conta_despesa',    from: 'conta_despesa',  type: 'boolean' },
      { name: 'conta_receita',    from: 'conta_receita',  type: 'boolean' },
      { name: 'totalizadora',     from: 'totalizadora',   type: 'boolean' },
      { name: 'transferencia',    from: 'transferencia',  type: 'boolean' },
      { name: 'nao_exibir',       from: 'nao_exibir',     type: 'boolean' },
      { name: 'inativa',          from: 'conta_inativa',  type: 'boolean' },
      { name: 'definida_usuario', from: 'definida_usuario', type: 'boolean' },
      { name: 'id_conta_contabil', from: 'id_conta_contabil' },
      { name: 'codigo_centro_receita_despesa', from: 'codigo_centro_receita_despesa' },
    ],
  },
  {
    name: 'departments',
    table: 'omie_departments',
    endpoint: 'geral/departamentos',
    action: 'ListarDepartamentos',
    listKey: 'departamentos',
    idFields: ['codigo', 'codigo_departamento'],
    tier: 'critical',
    phase: 1,
    purpose: 'Cost centers / departments',
    columns: [
      { name: 'codigo',           from: 'codigo' },
      { name: 'descricao',        from: 'descricao' },
      { name: 'estrutura',        from: 'estrutura' },
      { name: 'inativo',          from: 'inativo', type: 'boolean' },

    ],
  },
  {
    name: 'projects',
    table: 'omie_projects',
    endpoint: 'geral/projetos',
    action: 'ListarProjetos',
    listKey: 'cadastro',
    idFields: ['codigo', 'codint'],
    tier: 'critical',
    phase: 1,
    purpose: 'Cost sharing / projects',
    columns: [
      { name: 'codigo',           from: 'codigo' },
      { name: 'codint',           from: 'codint' },
      { name: 'nome',             from: 'nome' },
      { name: 'inativo',          from: 'inativo', type: 'boolean' },

    ],
  },
  {
    name: 'document_types',
    table: 'omie_document_types',
    endpoint: 'geral/tiposdoc',
    action: 'PesquisarTipoDocumento',
    listKey: 'tipo_documento_cadastro',
    idFields: ['codigo'],
    paginated: false,
    params: { codigo: '' },
    tier: 'critical',
    phase: 1,
    purpose: 'Document types (NF, BOL, DUP…)',
    columns: [
      { name: 'codigo',           from: 'codigo' },
      { name: 'descricao',        from: 'descricao' },
    ],
  },
  {
    name: 'units',
    table: 'omie_units',
    endpoint: 'geral/unidade',
    action: 'ListarUnidades',
    listKey: 'unidade_cadastro',
    idFields: ['codigo'],
    paginated: false,
    params: { codigo: '' },
    tier: 'critical',
    phase: 1,
    purpose: 'Units of measure (UN, KG, CX…)',
    columns: [
      { name: 'codigo',           from: 'codigo' },
      { name: 'descricao',        from: 'descricao' },
    ],
  },
  {
    name: 'familias_produtos',
    table: 'omie_familias_produtos',
    endpoint: 'geral/familias',
    action: 'PesquisarFamilias',
    listKey: 'familia_cadastro',
    idFields: ['codigo', 'inteiro_familia'],
    tier: 'critical',
    phase: 1,
    purpose: 'Product families / grouping',
    columns: [
      { name: 'codigo',                      from: 'codigo' },
      { name: 'codigo_familia_integracao',   from: 'codigo_familia_integracao' },
      { name: 'descricao',                   from: 'descricao' },
      { name: 'inteiro_familia',             from: 'inteiro_familia', type: 'bigint' },
      { name: 'inativa',                     from: 'inativa',         type: 'boolean' },
    ],
  },
  {
    name: 'billing_stages',
    table: 'omie_billing_stages',
    endpoint: 'produtos/etapafat',
    action: 'ListarEtapasFaturamento',
    listKey: 'cadastros',
    idFields: ['codigo'],
    tier: 'critical',
    phase: 1,
    purpose: 'Billing stages',
    columns: [
      { name: 'codigo',           from: 'codigo' },
      { name: 'descricao',        from: 'descricao' },
      { name: 'descricao_padrao', from: 'descricaoPadrao' },
      { name: 'inativo',          from: 'inativo', type: 'boolean' },

    ],
  },
  {
    name: 'order_steps',
    table: 'omie_order_steps',
    endpoint: 'produtos/etapaped',
    action: 'ListarEtapasPedido',
    listKey: 'cadastros',
    idFields: ['codigo'],
    tier: 'critical',
    phase: 1,
    purpose: 'Sales order pipeline steps',
    enabled: false,
    note: 'No /produtos/etapaped endpoint on Omie (returns 404). Order pipeline steps are usually configured statically — query `produtos/pedido/ListarPedidos` and group by `etapa` instead.',
  },
  {
    name: 'vendedores',
    table: 'omie_vendedores',
    endpoint: 'geral/vendedores',
    action: 'ListarVendedores',
    listKey: 'cadastro',
    idFields: ['codigo'],
    tier: 'critical',
    phase: 1,
    purpose: 'Sales team',
    columns: [
      { name: 'codigo',              from: 'codigo',                            type: 'bigint' },
      { name: 'codigo_integracao',   from: 'codigo_vendedor_integracao' },
      { name: 'nome',                from: 'nome' },
      { name: 'email',               from: 'email' },
      { name: 'fone',                from: 'fone' },
      { name: 'cpf',                 from: 'cpf' },
      { name: 'inativo',             from: 'inativo',                           type: 'boolean' },

    ],
  },
  {
    name: 'buyers',
    table: 'omie_buyers',
    endpoint: 'geral/comprador',
    action: 'ListarCompradores',
    listKey: 'cadastros',
    idFields: ['codigo', 'nCodComprador'],
    tier: 'optional',
    phase: 1,
    purpose: 'Purchasing team',
    enabled: false,
    note: 'No /geral/comprador endpoint on Omie (returns 404). Buyer info is embedded in purchase orders.',
  },
  {
    name: 'stock_locations',
    table: 'omie_stock_locations',
    endpoint: 'estoque/local',
    action: 'ListarLocaisEstoque',
    listKey: 'locaisEncontrados',
    idFields: ['codigo_local_estoque', 'codigo'],
    paginationStyle: 'new',
    tier: 'optional',
    phase: 1,
    purpose: 'Warehouses / stock locations',
    columns: [
      { name: 'codigo_local_estoque', from: 'codigo_local_estoque',              type: 'bigint' },
      { name: 'codigo',               from: 'codigo' },
      { name: 'descricao',            from: 'descricao' },
      { name: 'tipo',                 from: 'tipo' },
      { name: 'padrao',               from: 'padrao',                            type: 'boolean' },
      { name: 'inativo',              from: 'inativo',                           type: 'boolean' },

      { name: 'codigo_cliente',       from: 'codigo_cliente',                    type: 'bigint' },
      { name: 'disp_venda',           from: 'dispVenda',                         type: 'boolean' },
    ],
  },
  {
    name: 'banks',
    table: 'omie_banks',
    endpoint: 'geral/bancos',
    action: 'ListarBancos',
    listKey: 'ListarBancos',
    idFields: ['codigo', 'cCodigo'],
    tier: 'important',
    phase: 1,
    purpose: 'Bank lookup',
    columns: [
      { name: 'codigo', from: 'codigo' },
      { name: 'nome',   from: 'nome' },
      { name: 'tipo',   from: 'tipo' },
    ],
  },
  {
    name: 'payment_methods',
    table: 'omie_payment_methods',
    endpoint: 'geral/formaspagamento',
    action: 'ListarFormasPagamento',
    listKey: 'formas_pagamento_cadastro',
    idFields: ['cCodigo', 'codigo'],
    tier: 'important',
    phase: 1,
    purpose: 'Payment methods',
    enabled: false,
    note: 'No /geral/formaspagamento endpoint on Omie (returns 404). Payment-method codes (BOL, DIN, CRT…) come from `omie_document_types`.',
  },
  {
    name: 'parcelas',
    table: 'omie_parcelas',
    endpoint: 'geral/parcelas',
    action: 'ListarParcelas',
    listKey: 'parcelas_cadastro',
    idFields: ['cCodigo', 'codigo'],
    tier: 'important',
    phase: 1,
    purpose: 'Default payment conditions',
    columns: [
      { name: 'codigo',     from: 'cCodigo' },
      { name: 'descricao',  from: 'cDescricao' },
      { name: 'dias',       from: 'nDias',       type: 'numeric' },
      { name: 'percentual', from: 'nPercentual', type: 'numeric' },
    ],
  },
  {
    name: 'price_tables',
    table: 'omie_price_tables',
    endpoint: 'produtos/tabelaprecos',
    action: 'ListarTabelasPreco',
    listKey: 'tabelas_cadastro',
    idFields: ['nCodTabPreco', 'codigo'],
    paginationStyle: 'new',
    tier: 'optional',
    phase: 1,
    purpose: 'Differentiated pricing',
    columns: [
      { name: 'cod_tab_preco',     from: 'nCodTabPreco',    type: 'bigint' },
      { name: 'cod_int_tab_preco', from: 'cCodIntTabPreco' },
      { name: 'nome',              from: 'cNomeTabPreco' },
      { name: 'dt_ini',            from: 'dDtIni',          type: 'date' },
      { name: 'dt_fim',            from: 'dDtFim',          type: 'date' },
      { name: 'ativo',             from: 'cAtivo',          type: 'boolean' },
    ],
  },
  {
    name: 'crm_phases',
    table: 'omie_crm_phases',
    endpoint: 'crm/fases',
    action: 'ListarFases',
    listKey: 'cadastro',
    idFields: ['nCodFase', 'codigo'],
    tier: 'important',
    phase: 1,
    purpose: 'CRM opportunity phases',
    columns: [
      { name: 'cod_fase', from: 'nCodFase',  type: 'bigint' },
      { name: 'nome',     from: 'cNomeFase' },
    ],
  },
  {
    name: 'crm_status',
    table: 'omie_crm_status',
    endpoint: 'crm/status',
    action: 'ListarStatus',
    listKey: 'cadastro',
    idFields: ['nCodStatus', 'codigo'],
    tier: 'important',
    phase: 1,
    purpose: 'CRM opportunity statuses',
    columns: [
      { name: 'cod_status', from: 'nCodStatus',  type: 'bigint' },
      { name: 'nome',       from: 'cNomeStatus' },
    ],
  },
  {
    name: 'crm_origens',
    table: 'omie_crm_origens',
    endpoint: 'crm/origens',
    action: 'ListarOrigens',
    listKey: 'cadastro',
    idFields: ['nCodOrigem', 'codigo'],
    tier: 'important',
    phase: 1,
    purpose: 'Acquisition channels',
    columns: [
      { name: 'cod_origem', from: 'nCodOrigem',  type: 'bigint' },
      { name: 'nome',       from: 'cNomeOrigem' },
    ],
  },

  // ─── PHASE 2 — Transactional Financial ───────────────────────────────────

  {
    name: 'current_accounts',
    table: 'omie_current_accounts',
    endpoint: 'geral/contacorrente',
    action: 'ListarContasCorrentes',
    listKey: 'ListarContasCorrentes',
    idFields: ['nCodCC', 'codigo'],
    tier: 'critical',
    phase: 2,
    purpose: 'Bank current accounts / cards',
    columns: [
      { name: 'cod_cc',           from: 'nCodCC',           type: 'bigint' },
      { name: 'cod_cc_int',       from: 'cCodCCInt' },
      { name: 'descricao',        from: 'descricao' },
      { name: 'codigo_banco',     from: 'codigo_banco' },
      { name: 'codigo_agencia',   from: 'codigo_agencia' },
      { name: 'conta_corrente',   from: 'conta_corrente' },
      { name: 'tipo',             from: 'tipo' },
      { name: 'saldo_inicial',    from: 'saldo_inicial',    type: 'numeric' },
      { name: 'saldo_data',       from: 'saldo_data',       type: 'date' },
      { name: 'valor_limite',     from: 'valor_limite',     type: 'numeric' },
      { name: 'cnpj',             from: 'cnpj' },
      { name: 'doc_titular',      from: 'doc_titular' },
      { name: 'nome_titular',     from: 'nome_titular' },
      { name: 'observacao',       from: 'observacao' },
      { name: 'codigo_categoria', from: 'codigo_categoria' },
      { name: 'tipo_titular',     from: 'tipo_titular' },
      { name: 'inativo',          from: 'inativo',          type: 'boolean' },
      { name: 'fluxo_caixa', from: 'nao_fluxo', type: 'boolean_inverted' },

    ],
  },
  {
    name: 'financial_movements',
    table: 'omie_financial_movements',
    endpoint: 'financas/mf',
    action: 'ListarMovimentos',
    listKey: 'movimentos',
    idFields: [['detalhes.nCodTitulo', 'detalhes.cOrigem', 'detalhes.dDtPagamento', 'resumo.nValPago']],
    dedupKeyColumns: ['cod_titulo', 'origem', 'dt_pagamento', 'val_pago', 'natureza', 'cod_cc'],
    // Chave composta (corrigido 20/07/2026): nCodTitulo sozinho e
    // compartilhado por TODAS as parcelas/baixas de um mesmo titulo, e
    // nao diferencia registros diferentes -- causou R$15,5mi+ de
    // duplicidade acumulada em financial_movements (KMNO+RT). A
    // combinacao titulo+origem+data pagamento+valor pago identifica
    // cada movimento de forma unica e estavel entre syncs.
    paginationStyle: 'new',
    sinceDateField: 'dDtPagtoDe',
    sinceEndDateField: 'dDtPagtoAte',
    defaultSinceDays: 90,
    tier: 'critical',
    phase: 2,
    purpose: 'Cash flow / financial movements',
    columns: [
      // detalhes
      { name: 'cod_titulo',          from: 'detalhes.nCodTitulo',       type: 'bigint' },
      { name: 'cod_int_titulo',      from: 'detalhes.cCodIntTitulo' },
      { name: 'num_titulo',          from: 'detalhes.cNumTitulo' },
      { name: 'natureza',            from: 'detalhes.cNatureza' },
      { name: 'tipo',                from: 'detalhes.cTipo' },
      { name: 'status',              from: 'detalhes.cStatus' },
      { name: 'origem',              from: 'detalhes.cOrigem' },
      { name: 'operacao',            from: 'detalhes.cOperacao' },
      { name: 'cod_cliente',         from: 'detalhes.nCodCliente',      type: 'bigint' },
      { name: 'cpf_cnpj_cliente',    from: 'detalhes.cCPFCNPJCliente' },
      { name: 'cod_categoria',       from: 'detalhes.cCodCateg' },
      { name: 'cod_cc',              from: 'detalhes.nCodCC',           type: 'bigint' },
      { name: 'dt_emissao',          from: 'detalhes.dDtEmissao',       type: 'date' },
      { name: 'dt_vencimento',       from: 'detalhes.dDtVenc',          type: 'date' },
      { name: 'dt_previsao',         from: 'detalhes.dDtPrevisao',      type: 'date' },
      { name: 'dt_pagamento',        from: 'detalhes.dDtPagamento',     type: 'date' },
      { name: 'dt_registro',         from: 'detalhes.dDtRegistro',      type: 'date' },
      { name: 'dt_credito',          from: 'detalhes.dDtCredito',       type: 'date' },
      { name: 'dt_conciliacao',      from: 'detalhes.dDtConciliacao',   type: 'date' },
      { name: 'cod_origem',          from: 'detalhes.nCodOrigem',       type: 'bigint' },
      { name: 'cod_projeto',         from: 'detalhes.nCodProjeto',      type: 'bigint' },
      { name: 'cod_pedido',          from: 'detalhes.nCodPedido',       type: 'bigint' },
      { name: 'cod_os',              from: 'detalhes.nCodOS',           type: 'bigint' },
      { name: 'cod_titulo_repet',    from: 'detalhes.nCodTituloRepet',  type: 'bigint' },
      { name: 'valor_titulo',        from: 'detalhes.nValorTitulo',     type: 'numeric' },
      { name: 'percent_juros',       from: 'detalhes.nPercJuros',       type: 'numeric' },
      { name: 'percent_multa',       from: 'detalhes.nPercMulta',       type: 'numeric' },
      { name: 'percent_desconto',    from: 'detalhes.nPercDesconto',    type: 'numeric' },
      { name: 'valor_pis',           from: 'detalhes.nValorPIS',        type: 'numeric' },
      { name: 'valor_cofins',        from: 'detalhes.nValorCOFINS',     type: 'numeric' },
      { name: 'valor_csll',          from: 'detalhes.nValorCSLL',       type: 'numeric' },
      { name: 'valor_ir',            from: 'detalhes.nValorIR',         type: 'numeric' },
      { name: 'valor_iss',           from: 'detalhes.nValorISS',        type: 'numeric' },
      { name: 'valor_inss',          from: 'detalhes.nValorINSS',       type: 'numeric' },
      { name: 'num_doc_fiscal',      from: 'detalhes.cNumDocFiscal' },
      { name: 'numero_parcela',      from: 'detalhes.cNumParcela' },
      { name: 'observacao',          from: 'detalhes.cObs' },
      { name: 'cod_vendedor',        from: 'detalhes.cCodVendedor',     type: 'bigint' },
      // resumo
      { name: 'liquidado',           from: 'resumo.cLiquidado',         type: 'boolean' },
      { name: 'val_pago',            from: 'resumo.nValPago',           type: 'numeric' },
      { name: 'val_aberto',          from: 'resumo.nValAberto',         type: 'numeric' },
      { name: 'val_liquido',         from: 'resumo.nValLiquido',        type: 'numeric' },
      { name: 'val_juros',           from: 'resumo.nValJuros',          type: 'numeric' },
      { name: 'val_multa',           from: 'resumo.nValMulta',          type: 'numeric' },
      { name: 'val_desconto',        from: 'resumo.nValDesconto',       type: 'numeric' },
      // boleto
      { name: 'codigo_barras',       from: 'boleto.cCodBarras' },
      { name: 'numero_boleto',       from: 'boleto.cNumBoleto' },
      { name: 'nosso_numero',        from: 'boleto.cNossoNumero' },
      { name: 'url_boleto',          from: 'boleto.cURLBoleto' },
      // departamentos
      { name: 'cod_departamento',    from: 'departamentos.cCodDepartamento' },
      { name: 'percentual_departamento', from: 'departamentos.nPerDepto', type: 'numeric' },
    ],
    children: [
      {
        table: 'omie_financial_movements_categorias',
        listFrom: 'detalhes.aListaCateg',
        parentRefColumn: 'parent_omie_id',
        idFields: ['cCodCateg'],
        columns: [
          { name: 'cod_categoria',    from: 'cCodCateg' },
          { name: 'valor',            from: 'nValor',         type: 'numeric' },
          { name: 'percentual',       from: 'nPercentual',    type: 'numeric' },
          { name: 'cod_distribuicao', from: 'nCodDistr',      type: 'bigint' },
        ],
      },
    ],
  },
  {
    name: 'current_account_transactions',
    table: 'omie_current_account_transactions',
    endpoint: 'financas/contacorrentelancamentos',
    action: 'ListarLancCC',
    listKey: 'listaLancamentos',
    idFields: ['nCodLanc', 'codigo'],
    paginationStyle: 'new',
    sinceDateField: 'dDtAltDe',
    sinceEndDateField: 'dDtAltAte',
    defaultSinceDays: 90,
    tier: 'important',
    phase: 2,
    purpose: 'Bank transaction details',
    columns: [
      { name: 'cod_lanc',       from: 'nCodLanc',                type: 'bigint' },
      { name: 'cod_int_lanc',   from: 'cCodIntLanc' },
      { name: 'cod_agrup',      from: 'nCodAgrup',               type: 'bigint' },
      // cabecalho
      { name: 'cod_cc',         from: 'cabecalho.nCodCC',        type: 'bigint' },
      { name: 'dt_lanc',        from: 'cabecalho.dDtLanc',       type: 'date' },
      { name: 'dt_emissao',     from: 'cabecalho.dDtEmissao',    type: 'date' },
      { name: 'valor_lanc',     from: 'cabecalho.nValorLanc',    type: 'numeric' },
      // detalhes
      { name: 'cod_categoria',  from: 'detalhes.cCodCateg' },
      { name: 'tipo',           from: 'detalhes.cTipo' },
      { name: 'num_doc',        from: 'detalhes.cNumDoc' },
      { name: 'cod_cliente',    from: 'detalhes.nCodCliente',    type: 'bigint' },
      { name: 'cod_projeto',    from: 'detalhes.nCodProjeto',    type: 'bigint' },
      { name: 'cod_departamento', from: 'detalhes.cCodDepartamento' },
      { name: 'cod_titulo',     from: 'detalhes.nCodTitulo',     type: 'bigint' },
      { name: 'observacao',     from: 'detalhes.cObs' },
      // diversos
      { name: 'origem',         from: 'diversos.cOrigem' },
      { name: 'natureza',       from: 'diversos.cNatureza' },
      { name: 'dt_conciliacao', from: 'diversos.dDtConc',        type: 'date' },
    ],
  },

  // ─── PHASE 3 — Inventory ─────────────────────────────────────────────────

  {
    name: 'estoque_posicao',
    table: 'omie_estoque_posicao',
    endpoint: 'estoque/consulta',
    action: 'ListarPosEstoque',
    listKey: 'produtos',
    idFields: ['nCodProd', 'codigo_produto'],
    paginationStyle: 'new',
    tier: 'optional',
    phase: 3,
    purpose: 'Current stock balance',
    columns: [
      { name: 'cod_prod',             from: 'nCodProd',               type: 'bigint' },
      { name: 'cod_int',              from: 'cCodInt' },
      { name: 'codigo',               from: 'cCodigo' },
      { name: 'descricao',            from: 'cDescricao' },
      { name: 'ean',                  from: 'cEAN' },
      { name: 'unidade',              from: 'cUnidade' },
      { name: 'preco_unitario',       from: 'nPrecoUnitario',         type: 'numeric' },
      { name: 'saldo',                from: 'nSaldo',                 type: 'numeric' },
      { name: 'cmc',                  from: 'nCMC',                   type: 'numeric' },
      { name: 'pendente',             from: 'nPendente',              type: 'numeric' },
      { name: 'estoque_minimo',       from: 'estoque_minimo',         type: 'numeric' },
      { name: 'codigo_local_estoque', from: 'codigo_local_estoque',   type: 'bigint' },
      { name: 'reservado',            from: 'reservado',              type: 'numeric' },
      { name: 'fisico',               from: 'fisico',                 type: 'numeric' },
    ],
  },
  {
    name: 'estoque_movimentos',
    table: 'omie_estoque_movimentos',
    endpoint: 'estoque/movestoque',
    action: 'ListarMovimentos',
    listKey: 'cadastros',
    idFields: ['nCodProd'],
    sinceDateField: 'data_inicial',
    sinceEndDateField: 'data_final',
    defaultSinceDays: 90,
    tier: 'optional',
    phase: 3,
    purpose: 'Stock movement history (parent: product summary)',
    columns: [
      { name: 'cod_prod',         from: 'nCodProd',         type: 'bigint' },
      { name: 'cod_int_prod',     from: 'cCodIntProd' },
      { name: 'codigo',           from: 'cCodigo' },
      { name: 'descricao',        from: 'cDescricao' },
    ],
    children: [
      {
        table: 'omie_estoque_movimentos_lancamentos',
        listFrom: 'movimentos',
        parentRefColumn: 'parent_omie_id',
        idFields: ['nIdMovEst', 'nCodMov'],
        columns: [
          { name: 'id_mov_est',       from: 'nIdMovEst',       type: 'bigint' },
          { name: 'cod_mov',          from: 'nCodMov',         type: 'bigint' },
          { name: 'codigo_local',     from: 'codigo_local_estoque', type: 'bigint' },
          { name: 'dt_movimento',     from: 'dDtMov',          type: 'date' },
          { name: 'tipo_movimento',   from: 'cTipoMov' },
          { name: 'origem',           from: 'cOrigem' },
          { name: 'numero_documento', from: 'cNumDoc' },
          { name: 'observacao',       from: 'cObs' },
          { name: 'quantidade',       from: 'nQtde',           type: 'numeric' },
          { name: 'valor_unitario',   from: 'nValUnit',        type: 'numeric' },
          { name: 'valor_total',      from: 'nValTotal',       type: 'numeric' },
          { name: 'saldo_inicial',    from: 'nSaldoIni',       type: 'numeric' },
          { name: 'saldo_final',      from: 'nSaldoFim',       type: 'numeric' },
          { name: 'cmc_inicial',      from: 'nCMCIni',         type: 'numeric' },
          { name: 'cmc_final',        from: 'nCMCFim',         type: 'numeric' },
          { name: 'id_pedido',        from: 'nIdPedido',       type: 'bigint' },
          { name: 'id_lote',          from: 'nIdLote',         type: 'bigint' },
          { name: 'id_ajuste',        from: 'nIdAjuste',       type: 'bigint' },
        ],
      },
    ],
  },
  {
    name: 'stock_adjustments',
    table: 'omie_stock_adjustments',
    endpoint: 'estoque/ajuste',
    action: 'ListarAjustes',
    listKey: 'cadastros',
    idFields: ['nIdAjuste', 'codigo'],
    tier: 'optional',
    phase: 3,
    purpose: 'Stock losses / adjustments / counting',
    enabled: false,
    note: 'Omie has no consolidated /estoque/ajuste/ListarAjustes endpoint. Adjustments surface as records in `omie_estoque_movimentos_lancamentos` with `origem="AJU"` and `id_ajuste` set.',
  },

  // ─── PHASE 4 — Purchases ─────────────────────────────────────────────────

  {
    name: 'orders_purchase',
    table: 'omie_orders_purchase',
    endpoint: 'produtos/pedidocompra',
    action: 'PesquisarPedCompra',
    listKey: 'pedidos_pesquisa',
    idFields: ['nCodPedido', 'codigo_pedido'],
    paginationStyle: 'pedidocompra',
    sinceDateField: 'dDataInicial',
    sinceEndDateField: 'dDataFinal',
    defaultSinceDays: 365,
    params: {
      lApenasImportadoApi: 'F',
      lExibirPedidosPendentes: 'T',
      lExibirPedidosFaturados: 'T',
      lExibirPedidosRecebidos: 'T',
      lExibirPedidosCancelados: 'T',
      lExibirPedidosEncerrados: 'T',
      lExibirPedidosRecParciais: 'T',
      lExibirPedidosFatParciais: 'T',
      lApenasAlterados: 'F',
    },
    tier: 'optional',
    phase: 4,
    purpose: 'Purchase orders (in flight)',
    columns: [
      { name: 'cod_pedido',          from: 'nCodPedido',         type: 'bigint' },
      { name: 'numero_pedido',       from: 'cNumero' },
      { name: 'cod_fornecedor',      from: 'nCodFornecedor',     type: 'bigint' },
      { name: 'cod_comprador',       from: 'nCodComprador',      type: 'bigint' },
      { name: 'dt_emissao',          from: 'dDtEmissao',         type: 'date' },
      { name: 'dt_previsao',         from: 'dDtPrevisao',        type: 'date' },
      { name: 'valor_total',         from: 'nValorTotal',        type: 'numeric' },
      { name: 'valor_mercadorias',   from: 'nValorMercadorias',  type: 'numeric' },
      { name: 'valor_frete',         from: 'nValorFrete',        type: 'numeric' },
      { name: 'valor_desconto',      from: 'nValorDesconto',     type: 'numeric' },
      { name: 'status',              from: 'cStatus' },
      { name: 'observacoes',         from: 'cObservacoes' },
    ],
  },
  {
    name: 'notas_entrada',
    table: 'omie_notas_entrada',
    endpoint: 'produtos/notaentrada',
    action: 'ListarNotaEnt',
    listKey: 'notas',
    idFields: ['nIdNF', 'nIdNfEnt'],
    paginationStyle: 'nfe',
    sinceDateField: 'dtAltDe',
    sinceEndDateField: 'dtAltAte',
    defaultSinceDays: 365,
    tier: 'optional',
    phase: 4,
    purpose: 'Inbound invoices (physical receipt)',
    columns: [
      { name: 'id_nf',          from: 'nIdNF',         type: 'bigint' },
      { name: 'id_nf_ent',      from: 'nIdNfEnt',      type: 'bigint' },
      { name: 'num_doc',        from: 'cNumDoc' },
      { name: 'serie',          from: 'cSerie' },
      { name: 'modelo',         from: 'cModelo' },
      { name: 'dt_emissao',     from: 'dEmissao',      type: 'date' },
      { name: 'dt_entrada',     from: 'dEntrada',      type: 'date' },
      { name: 'cnpj_cpf',       from: 'cnpj_cpf' },
      { name: 'razao_social',   from: 'cRazaoSocial' },
      { name: 'valor_nota',     from: 'nValorNota',    type: 'numeric' },
      { name: 'valor_total',    from: 'nValorTotal',   type: 'numeric' },
      { name: 'valor_desconto', from: 'nValorDesconto', type: 'numeric' },
      { name: 'cfop',           from: 'cCFOP' },
      { name: 'tipo_operacao',  from: 'cTipoOper' },
      { name: 'observacoes',    from: 'cObservacoes' },
    ],
  },

  // ─── PHASE 5 — Issued Invoices ───────────────────────────────────────────

  {
    name: 'nfe',
    table: 'omie_nfe',
    endpoint: 'produtos/nfconsultar',
    action: 'ListarNF',
    listKey: 'nfCadastro',
    idFields: ['compl.nIdNF'],
    sinceDateField: 'dEmiInicial',
    sinceEndDateField: 'dEmiFinal',
    defaultSinceDays: 90,
    tier: 'optional',
    phase: 5,
    purpose: 'Issued NF-e',
    columns: [
      // nfCabecalho
      { name: 'id_nf',           from: 'compl.nIdNF',       type: 'bigint' },
      { name: 'cod_nf',          from: 'nfCabecalho.nCodNF',      type: 'bigint' },
      { name: 'numero_nf',       from: 'ide.nNF' },
      { name: 'serie',           from: 'ide.serie' },
      { name: 'modelo',          from: 'ide.mod' },
      { name: 'tipo_nf',         from: 'ide.tpNF' },
      { name: 'tipo_ambiente',   from: 'ide.tpAmb' },
      { name: 'chave_nfe',       from: 'compl.cChaveNFe' },
      { name: 'codigo_categoria', from: 'compl.cCodCateg' },
      { name: 'natureza_operacao', from: 'nfCabecalho.natOp' },
      { name: 'dt_emissao',      from: 'ide.dEmi',        type: 'date' },
      { name: 'dt_saida',        from: 'ide.dSaiEnt',     type: 'date' },
      { name: 'finalidade',      from: 'ide.finNFe' },
      { name: 'dt_cancelamento', from: 'ide.dCan',        type: 'date' },
      { name: 'denegada',        from: 'ide.cDeneg' },
      { name: 'dt_inutilizacao', from: 'ide.dInut',       type: 'date' },
      { name: 'consumidor_final', from: 'nfCabecalho.indFinal' },
      { name: 'indicador_presenca', from: 'nfCabecalho.indPres' },
      // nfDestInt
      { name: 'cod_cliente',     from: 'nfDestInt.nCodCli',    type: 'bigint' },
      { name: 'cnpj_cpf',        from: 'nfDestInt.cnpj_cpf' },
      { name: 'razao_social',    from: 'nfDestInt.cRazao' },
      { name: 'email_dest',      from: 'nfDestInt.email' },
      { name: 'endereco_dest',   from: 'nfDestInt.xLgr' },
      { name: 'numero_dest',     from: 'nfDestInt.nro' },
      { name: 'complemento_dest', from: 'nfDestInt.xCpl' },
      { name: 'bairro_dest',     from: 'nfDestInt.xBairro' },
      { name: 'municipio_dest',  from: 'nfDestInt.xMun' },
      { name: 'cmun_dest',       from: 'nfDestInt.cMun' },
      { name: 'uf_dest',         from: 'nfDestInt.UF' },
      { name: 'cep_dest',        from: 'nfDestInt.CEP' },
      // total.ICMSTot
      { name: 'valor_bc_icms',   from: 'total.ICMSTot.vBC',     type: 'numeric' },
      { name: 'valor_icms',      from: 'total.ICMSTot.vICMS',   type: 'numeric' },
      { name: 'valor_bc_icms_st', from: 'total.ICMSTot.vBCST',  type: 'numeric' },
      { name: 'valor_st',        from: 'total.ICMSTot.vST',     type: 'numeric' },
      { name: 'valor_prod',      from: 'total.ICMSTot.vProd',   type: 'numeric' },
      { name: 'valor_frete',     from: 'total.ICMSTot.vFrete',  type: 'numeric' },
      { name: 'valor_seguro',    from: 'total.ICMSTot.vSeg',    type: 'numeric' },
      { name: 'valor_desconto',  from: 'total.ICMSTot.vDesc',   type: 'numeric' },
      { name: 'valor_outras',    from: 'total.ICMSTot.vOutro',  type: 'numeric' },
      { name: 'valor_ipi',       from: 'total.ICMSTot.vIPI',    type: 'numeric' },
      { name: 'valor_pis',       from: 'total.ICMSTot.vPIS',    type: 'numeric' },
      { name: 'valor_cofins',    from: 'total.ICMSTot.vCOFINS', type: 'numeric' },
      { name: 'valor_nota',      from: 'total.ICMSTot.vNF',     type: 'numeric' },
      // transp
      { name: 'modalidade_frete', from: 'compl.cModFrete' },
      { name: 'cnpj_transportadora', from: 'transp.transporta.CNPJ' },
      { name: 'razao_transportadora', from: 'transp.transporta.xNome' },
      { name: 'ie_transportadora', from: 'transp.transporta.IE' },
      // emitNFe (some tenants)
      { name: 'cnpj_emit',       from: 'emitNFe.CNPJ' },
      // compl
      { name: 'inf_complementar', from: 'compl.infCpl' },
      { name: 'inf_adic_fisco',  from: 'compl.infAdFisco' },
    ],
    children: [
      {
        table: 'omie_nfe_items',
        listFrom: 'det',
        parentRefColumn: 'parent_omie_id',
        idFields: ['nItem'],
        columns: [
          { name: 'n_item',             from: 'nfProdInt.nCodItem',                              type: 'bigint' },
          // prod
          { name: 'cprod',              from: 'prod.cProd' },
          { name: 'cean',               from: 'prod.cEAN' },
          { name: 'descricao',          from: 'prod.xProd' },
          { name: 'ncm',                from: 'prod.NCM' },
          { name: 'cest',               from: 'prod.CEST' },
          { name: 'cfop',               from: 'prod.CFOP' },
          { name: 'unidade_comercial',  from: 'prod.uCom' },
          { name: 'quantidade_comercial', from: 'prod.qCom',                        type: 'numeric' },
          { name: 'valor_unitario',     from: 'prod.vUnCom',                        type: 'numeric' },
          { name: 'valor_produto',      from: 'prod.vProd',                         type: 'numeric' },
          { name: 'unidade_tributada',  from: 'prod.uTrib' },
          { name: 'quantidade_tributada', from: 'prod.qTrib',                       type: 'numeric' },
          { name: 'valor_unit_tributado', from: 'prod.vUnTrib',                     type: 'numeric' },
          { name: 'valor_desconto',     from: 'prod.vDesc',                         type: 'numeric' },
          { name: 'valor_frete',        from: 'prod.vFrete',                        type: 'numeric' },
          { name: 'valor_seguro',       from: 'prod.vSeg',                          type: 'numeric' },
          { name: 'valor_outras',       from: 'prod.vOutro',                        type: 'numeric' },
          // imposto
          { name: 'icms_cst',           from: 'imposto.ICMS.CST' },
          { name: 'icms_origem',        from: 'imposto.ICMS.orig' },
          { name: 'icms_vbc',           from: 'imposto.ICMS.vBC',                   type: 'numeric' },
          { name: 'icms_pbc',           from: 'imposto.ICMS.pICMS',                 type: 'numeric' },
          { name: 'icms_valor',         from: 'imposto.ICMS.vICMS',                 type: 'numeric' },
          { name: 'ipi_cst',            from: 'imposto.IPI.CST' },
          { name: 'ipi_valor',          from: 'imposto.IPI.vIPI',                   type: 'numeric' },
          { name: 'pis_cst',            from: 'imposto.PIS.CST' },
          { name: 'pis_valor',          from: 'imposto.PIS.vPIS',                   type: 'numeric' },
          { name: 'cofins_cst',         from: 'imposto.COFINS.CST' },
          { name: 'cofins_valor',       from: 'imposto.COFINS.vCOFINS',             type: 'numeric' },
        ],
      },
    ],
  },
  {
    name: 'nfse',
    table: 'omie_nfse',
    endpoint: 'servicos/nfseconsultar',
    action: 'ListarNFSE',
    listKey: 'nfseCadastro',
    idFields: ['nIdNfse', 'nCodNFSe'],
    paginationStyle: 'nfe',
    sinceDateField: 'dDtInicial',
    sinceEndDateField: 'dDtFinal',
    defaultSinceDays: 90,
    tier: 'optional',
    phase: 5,
    purpose: 'Issued NFS-e',
    enabled: false,
    note: '/servicos/nfseconsultar returned 404 in this tenant. Confirm with Omie support that the NFS-e add-on is licensed, then flip enabled:true.',
  },
  {
    name: 'boletos',
    table: 'omie_boletos',
    endpoint: 'financas/contareceberboleto',
    action: 'ListarBoletos',
    listKey: 'boletos',
    idFields: ['nCodBoleto', 'codigo_lancamento_omie'],
    tier: 'optional',
    phase: 5,
    purpose: 'Generated payment slips',
    enabled: false,
    note: 'No standalone /financas/contareceberboleto/ListarBoletos endpoint. Boleto data lives on `omie_accounts_receivable` rows (boleto.* fields).',
  },
  {
    name: 'pix',
    table: 'omie_pix',
    endpoint: 'financas/pix',
    action: 'ListarPix',
    listKey: 'pix',
    idFields: ['nCodPix', 'codigo'],
    tier: 'optional',
    phase: 5,
    purpose: 'PIX collections',
    enabled: false,
    note: 'No standalone /financas/pix/ListarPix endpoint. PIX info travels in `omie_financial_movements` (tipo=PIX) and `omie_accounts_receivable`.',
  },

  // ─── PHASE 6 — CRM extras ────────────────────────────────────────────────

  {
    name: 'crm_contatos',
    table: 'omie_crm_contatos',
    endpoint: 'crm/contatos',
    action: 'ListarContatos',
    listKey: 'cadastros',
    idFields: ['nCod', 'nCodContato', 'codigo'],
    tier: 'optional',
    phase: 6,
    purpose: 'People in CRM accounts',
    columns: [
      { name: 'cod',          from: 'nCod',          type: 'bigint' },
      { name: 'cod_int',      from: 'cCodInt' },
      { name: 'nome',         from: 'cNome' },
      { name: 'sobrenome',    from: 'cSobrenome' },
      { name: 'cargo',        from: 'cCargo' },
      { name: 'email',        from: 'cEmail' },
      { name: 'fone',         from: 'cFone' },
      { name: 'cod_conta',    from: 'nCodConta',     type: 'bigint' },
      { name: 'cpf',          from: 'cCPF' },
      { name: 'inativo',      from: 'cInativo',      type: 'boolean' },

    ],
  },

  // ─── PHASE 7 — Industry-specific (off by default) ────────────────────────

  {
    name: 'products_variation',
    table: 'omie_products_variation',
    endpoint: 'geral/produtocaract',
    action: 'ListarVariacoes',
    listKey: 'cadastros',
    idFields: ['nCodVariacao', 'codigo'],
    tier: 'industry',
    phase: 7,
    purpose: 'Retail SKU variations (color, size)',
    columns: [
      { name: 'cod_variacao', from: 'nCodVariacao',  type: 'bigint' },
      { name: 'cod_produto',  from: 'nCodProduto',   type: 'bigint' },
      { name: 'descricao',    from: 'cDescricao' },
      { name: 'codigo',       from: 'cCodigo' },
    ],
  },
  {
    name: 'products_kit',
    table: 'omie_products_kit',
    endpoint: 'geral/produtoskit',
    action: 'ListarKits',
    listKey: 'kits_cadastro',
    idFields: ['codigo', 'codigo_produto'],
    tier: 'industry',
    phase: 7,
    purpose: 'Combos / baskets',
    columns: [
      { name: 'codigo',        from: 'codigo' },
      { name: 'codigo_produto', from: 'codigo_produto', type: 'bigint' },
      { name: 'descricao',     from: 'descricao' },
    ],
  },
  {
    name: 'products_lot',
    table: 'omie_products_lot',
    endpoint: 'estoque/lote',
    action: 'ListarLotes',
    listKey: 'lotes',
    idFields: ['nIdLote', 'codigo'],
    tier: 'industry',
    phase: 7,
    purpose: 'Regulated industry traceability',
    columns: [
      { name: 'id_lote',       from: 'nIdLote',       type: 'bigint' },
      { name: 'cod_prod',      from: 'nCodProd',      type: 'bigint' },
      { name: 'descricao',     from: 'cDescricao' },
      { name: 'numero_lote',   from: 'cNumeroLote' },
      { name: 'data_validade', from: 'dValidade',     type: 'date' },
      { name: 'quantidade',    from: 'nQuantidade',   type: 'numeric' },
    ],
  },
  {
    name: 'products_structure',
    table: 'omie_products_structure',
    endpoint: 'geral/produtoestrutura',
    action: 'ListarEstruturas',
    listKey: 'estruturas',
    idFields: ['nIdEstrutura', 'codigo'],
    tier: 'industry',
    phase: 7,
    purpose: 'Industrial BOM',
    columns: [
      { name: 'id_estrutura',  from: 'nIdEstrutura',  type: 'bigint' },
      { name: 'cod_prod',      from: 'nCodProd',      type: 'bigint' },
      { name: 'descricao',     from: 'cDescricao' },
    ],
  },
  {
    name: 'orders_production',
    table: 'omie_orders_production',
    endpoint: 'producao/op',
    action: 'ListarOPs',
    listKey: 'ops',
    idFields: ['nIdOp', 'nCodOp'],
    tier: 'industry',
    phase: 7,
    purpose: 'Manufacturing orders',
    columns: [
      { name: 'id_op',         from: 'nIdOp',         type: 'bigint' },
      { name: 'cod_op',        from: 'nCodOp',        type: 'bigint' },
      { name: 'numero_op',     from: 'cNumOp' },
      { name: 'dt_emissao',    from: 'dDtEmissao',    type: 'date' },
      { name: 'dt_previsao',   from: 'dDtPrevisao',   type: 'date' },
      { name: 'status',        from: 'cStatus' },
      { name: 'cod_prod',      from: 'nCodProd',      type: 'bigint' },
      { name: 'quantidade',    from: 'nQtde',         type: 'numeric' },
    ],
  },
  {
    name: 'service_contracts',
    table: 'omie_service_contracts',
    endpoint: 'servicos/contratoservico',
    action: 'ListarContratos',
    listKey: 'contratoCadastro',
    idFields: ['nCodCtr', 'nIdContrato'],
    tier: 'industry',
    phase: 7,
    purpose: 'Recurring services (SaaS, monthly fee)',
    columns: [
      { name: 'cod_ctr',       from: 'cabecalho.nCodCtr',    type: 'bigint' },
      { name: 'numero_ctr',    from: 'cabecalho.cNumCtr' },
      { name: 'cod_cliente',   from: 'cabecalho.nCodCli',    type: 'bigint' },
      { name: 'dt_validade',   from: 'cabecalho.dDtValidade', type: 'date' },
      { name: 'periodicidade', from: 'cabecalho.cPeriodicidade' },
    ],
  },
  {
    name: 'cte',
    table: 'omie_cte',
    endpoint: 'produtos/cte',
    action: 'ListarCTE',
    listKey: 'cteCadastro',
    idFields: ['nIdCTe', 'nCodCTe'],
    paginationStyle: 'nfe',
    sinceDateField: 'dEmiInicial',
    sinceEndDateField: 'dEmiFinal',
    defaultSinceDays: 90,
    tier: 'industry',
    phase: 7,
    purpose: 'Shipping company CT-e',
    columns: [
      { name: 'id_cte',     from: 'cteCabecalho.nIdCTe',  type: 'bigint' },
      { name: 'cod_cte',    from: 'cteCabecalho.nCodCTe', type: 'bigint' },
      { name: 'numero_cte', from: 'cteCabecalho.nCT' },
      { name: 'serie',      from: 'cteCabecalho.serie' },
      { name: 'chave_cte',  from: 'cteCabecalho.cChaveCTe' },
      { name: 'dt_emissao', from: 'cteCabecalho.dEmi',    type: 'date' },
      { name: 'valor',      from: 'totalCTe.vTPrest',     type: 'numeric' },
    ],
  },
  {
    name: 'fiscal_coupon',
    table: 'omie_fiscal_coupon',
    endpoint: 'produtos/nfceconsultar',
    action: 'ListarNFCE',
    listKey: 'nfceCadastro',
    idFields: ['nIdNFCe', 'nCodNFCe'],
    paginationStyle: 'nfe',
    sinceDateField: 'dEmiInicial',
    sinceEndDateField: 'dEmiFinal',
    defaultSinceDays: 90,
    tier: 'industry',
    phase: 7,
    purpose: 'Retail POS NFC-e / SAT',
    columns: [
      { name: 'id_nfce',    from: 'nfceCabecalho.nIdNFCe',  type: 'bigint' },
      { name: 'cod_nfce',   from: 'nfceCabecalho.nCodNFCe', type: 'bigint' },
      { name: 'numero_nfce', from: 'nfceCabecalho.nNFCe' },
      { name: 'chave_nfce', from: 'nfceCabecalho.cChaveNFCe' },
      { name: 'dt_emissao', from: 'nfceCabecalho.dEmi',     type: 'date' },
      { name: 'valor_nfce', from: 'totalNFCe.ICMSTot.vNF',  type: 'numeric' },
    ],
  },
  {
    name: 'tags',
    table: 'omie_tags',
    endpoint: 'geral/tags',
    action: 'ListarTags',
    listKey: 'tags_cadastro',
    idFields: ['nCodTag', 'codigo'],
    tier: 'industry',
    phase: 7,
    purpose: 'Tags for clients / suppliers',
    columns: [
      { name: 'cod_tag', from: 'nCodTag',  type: 'bigint' },
      { name: 'tag',     from: 'cNomeTag' },
    ],
  },
  {
    name: 'caracteristicas_clientes',
    table: 'omie_caracteristicas_clientes',
    endpoint: 'geral/clientescaract',
    action: 'ListarCaract',
    listKey: 'caracteristicas_cadastro',
    idFields: ['nCodCaract', 'codigo'],
    tier: 'industry',
    phase: 7,
    purpose: 'Custom fields on clients',
    columns: [
      { name: 'cod_caract', from: 'nCodCaract',     type: 'bigint' },
      { name: 'nome',       from: 'cNomeCaract' },
      { name: 'tipo',       from: 'cTipoCaract' },
    ],
  },
  {
    name: 'product_characteristics',
    table: 'omie_product_characteristics',
    endpoint: 'geral/produtoscaract',
    action: 'ListarCaract',
    listKey: 'caracteristicas_cadastro',
    idFields: ['nCodCaract', 'codigo'],
    tier: 'industry',
    phase: 7,
    purpose: 'Custom field definitions on products',
    columns: [
      { name: 'cod_caract', from: 'nCodCaract',     type: 'bigint' },
      { name: 'nome',       from: 'cNomeCaract' },
      { name: 'tipo',       from: 'cTipoCaract' },
    ],
  },
];

/**
 * Decide whether an entry should be active for the current run, based
 * on per-entry `enabled` overrides and the OMIE_SYNC_TIERS env var.
 *
 * Legacy entries (phase 0) are always-on regardless of tier filter.
 */
function isEnabled(entry, enabledTiers) {
  if (typeof entry.enabled === 'boolean') return entry.enabled;
  if (entry.legacy) return true;
  if (enabledTiers.includes('all')) return true;
  return enabledTiers.includes(entry.tier);
}

function getEnabledTiers() {
  return (process.env.OMIE_SYNC_TIERS || 'critical,important,optional')
    .toLowerCase()
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
}

function activeTables() {
  const enabledTiers = getEnabledTiers();
  return TABLES.filter((entry) => isEnabled(entry, enabledTiers));
}

module.exports = {
  TABLES,
  activeTables,
  isEnabled,
  getEnabledTiers,
};


